name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.6

      - name: Install garble
        run: go install mvdan.cc/garble@latest

      - name: Get version tag
        id: get_version
        run: echo "VERSION_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          suffix=""
          if [ "${{ matrix.goos }}" == "windows" ]; then suffix=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} garble -tiny build -o dist/git-secrets-replacer-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.VERSION_TAG }}${suffix}

      - name: Create Linux zip file
        if: matrix.goos == 'linux'
        run: |
          cat > dist/terminal.sh << EOL
          #!/bin/bash
          DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
          "\$DIR/git-secrets-replacer-linux-${{ matrix.goarch }}-${{ env.VERSION_TAG }}"
          EOL
          chmod +x dist/terminal.sh
          zip -j "dist/git-secrets-replacer-linux-${{ matrix.goarch }}-${{ env.VERSION_TAG }}.zip" "dist/git-secrets-replacer-linux-${{ matrix.goarch }}-${{ env.VERSION_TAG }}" "dist/terminal.sh"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: git-secrets-replacer-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.VERSION_TAG }}
          path: |
            dist/git-secrets-replacer-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.VERSION_TAG }}*
            dist/git-secrets-replacer-linux-${{ matrix.goos }}-${{ env.VERSION_TAG }}.zip

  release:
    runs-on: ubuntu-latest
    needs: [build]
  
    steps:
      - name: Get version tag
        run: echo "VERSION_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
  
      - name: Download build artifacts for linux-amd64
        uses: actions/download-artifact@v3
        with:
          name: git-secrets-replacer-linux-amd64-${{ env.VERSION_TAG }}
          path: dist
  
      - name: Download build artifacts for linux-arm64
        uses: actions/download-artifact@v3
        with:
          name: git-secrets-replacer-linux-arm64-${{ env.VERSION_TAG }}
          path: dist
  
      - name: Download build artifacts for windows-amd64
        uses: actions/download-artifact@v3
        with:
          name: git-secrets-replacer-windows-amd64-${{ env.VERSION_TAG }}
          path: dist
  
      - name: Download build artifacts for windows-arm64
        uses: actions/download-artifact@v3
        with:
          name: git-secrets-replacer-windows-arm64-${{ env.VERSION_TAG }}
          path: dist
  
      - name: List dist directory contents for debugging
        run: ls -R dist
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/git-secrets-replacer-linux-amd64-${{ env.VERSION_TAG }}.zip
            dist/git-secrets-replacer-linux-arm64-${{ env.VERSION_TAG }}.zip
            dist/git-secrets-replacer-windows-amd64-${{ env.VERSION_TAG }}.exe
            dist/git-secrets-replacer-windows-arm64-${{ env.VERSION_TAG }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
